Repository Crustaly/audemywebsite, pull requests merged in 2025-03, with the labels that each got.

#61 Updated Login
  src/pages/LogIn/LogIn.vue
Labels: enhancement

#79 Fix: Speech Recognition Responsiveness and Continuous Mode Implementation
  src/Utilities/speechRecognition.js
  src/pages/GameZone/GameZoneList/AdditionGame.vue
  src/pages/GameZone/GameZoneList/CarCounting.vue
  src/pages/GameZone/GameZoneList/ColorGame.vue
  src/pages/GameZone/GameZoneList/DefinitionDetective.vue
  src/pages/GameZone/GameZoneList/DivisionDuel.vue
  src/pages/GameZone/GameZoneList/FruitFrenzy.vue
  src/pages/GameZone/GameZoneList/MonkeyMadness.vue
  src/pages/GameZone/GameZoneList/MultiplicationMadness.vue
  src/pages/GameZone/GameZoneList/OddOneOut.vue
  src/pages/GameZone/GameZoneList/PartOfSpeech.vue
  src/pages/GameZone/GameZoneList/PolarPairing.vue
  src/pages/GameZone/GameZoneList/ShapeShark.vue
  src/pages/GameZone/GameZoneList/SpellingBee.vue
  src/pages/GameZone/GameZoneList/SubtractionGame.vue
  src/pages/GameZone/GameZoneList/SyllableSorting.vue
  src/pages/GameZone/GameZoneList/Vocab.vue
Labels: feature, breaking-change

#82 Fix/mobile compatibility
  src/Utilities/playAudio.js
  src/pages/GameZone/GameZoneList/AdditionGame.vue
  src/pages/GameZone/GameZoneList/CarCounting.vue
  src/pages/GameZone/GameZoneList/ColorGame.vue
  src/pages/GameZone/GameZoneList/DefinitionDetective.vue
  src/pages/GameZone/GameZoneList/DivisionDuel.vue
  src/pages/GameZone/GameZoneList/FruitFrenzy.vue
  src/pages/GameZone/GameZoneList/MonkeyMadness.vue
  src/pages/GameZone/GameZoneList/MultiplicationMadness.vue
  src/pages/GameZone/GameZoneList/OddOneOut.vue
  src/pages/GameZone/GameZoneList/PartOfSpeech.vue
  src/pages/GameZone/GameZoneList/PolarPairing.vue
  src/pages/GameZone/GameZoneList/ShapeShark.vue
  src/pages/GameZone/GameZoneList/SpellingBee.vue
  src/pages/GameZone/GameZoneList/SubtractionGame.vue
  src/pages/GameZone/GameZoneList/SyllableSorting.vue
  src/pages/GameZone/GameZoneList/Vocab.vue
Labels: feature
