Repository Crustaly/audemywebsite, pull requests merged in 2025-08, with the labels that each got.

#234 Chore: Prettier fix
  src/pages/Home/Testimonials/Testimonials.vue
  src/pages/Impact/CollaboratingSchools/Affiliates.vue
  src/pages/Impact/CollaboratingSchools/Map.vue
  src/pages/Impact/OurReach/OurReach.vue
  src/pages/OurProjects/ProjectsInAction/ProjectsInAction.vue
Labels: documentation, priority: low

#236 fix: Game pages WCAG contrast, UI consistency, & RWD
  public/assets/gameImages/buttons/info.png
  public/assets/gameImages/buttons/mic.png
  public/assets/gameImages/buttons/repeat.png
  public/assets/gameImages/cloud-bg-Tab-left.png
  public/assets/gameImages/cloud-bg-Tab-right.png
  public/assets/gameImages/cloud-bg.png
  public/assets/gameImages/moon.png
  public/assets/gameImages/pencil.png
  public/assets/gameImages/rainbow.png
  public/assets/gameImages/shooting-star.png
  public/assets/gameImages/stars-clouds.png
  src/components/Game/GameControls.vue
  src/components/Game/GameHeader.vue
  src/components/Game/GameLayout.vue
  src/components/Game/GameOver.vue
  src/components/Game/PlayButton.vue
  src/components/Game/StartQuestionsButton.vue
  src/composables/useGameUI.js
  src/config/gameConfigs.js
  src/pages/Footer/GamePagesFooter.vue
  src/pages/GameZone/GameZoneList/CarCounting.vue
  src/pages/GameZone/GameZoneList/SpellingBee.vue
  src/pages/Header/GamePagesHeader.vue
  src/style.css
Labels: bug, feature, accessibility, refactor

#240 refactor: add reusable Game Zone button components & DRY up logic
  src/pages/GameZone/GameZone.vue
  src/pages/GameZone/GameZoneFilters/GameDropdownOptions.vue
  src/pages/GameZone/GameZoneFilters/GameMenuButton.vue
Labels: refactor

#262 fix: RWD for Impact Page components & missing `<ResearchListCard/>` URLs
  public/assets/images/our-projects/Research_paper1.png
  public/assets/images/our-projects/Research_paper2.png
  public/assets/images/our-projects/Research_paper3.png
  public/assets/images/our-projects/acm-chi-paper-3.png
  public/assets/images/our-projects/audiotactcle-sys-paper-1.png
  public/assets/images/our-projects/carl-trophy.png
  public/assets/images/our-projects/classroom.svg
  public/assets/images/our-projects/heard-le-paper-2.png
  public/assets/images/our-projects/primary-school.png
  public/assets/images/our-projects/researchtech/chat.png
  public/assets/images/our-projects/researchtech/digital.png
  public/assets/images/our-projects/researchtech/eye.svg
  public/assets/images/our-projects/researchtech/message-chat.svg
  public/assets/images/our-projects/researchtech/message.png
  public/assets/images/our-projects/researchtech/volume-up.png
  public/assets/images/our-projects/school.svg
  public/assets/images/our-projects/whiteboard.png
  src/pages/Impact/Accolades/AccoladesCard.vue
  src/pages/OurProjects/Events/HaveYouHeard/HaveYouHeard.vue
  src/pages/OurProjects/Events/HaveYouHeard/HaveYouHeardCard/HaveYouHeardCard.vue
  src/pages/OurProjects/Events/KatyYouthHacks/KatyYouthHacks.vue
  src/pages/OurProjects/ResearchTech/Card/Card.vue
  src/pages/OurProjects/ResearchTech/Research/ResearchListCard.vue
  src/pages/OurProjects/ResearchTech/ResearchTech.vue
  src/pages/OurProjects/Social/SocialMedia.vue
Labels: bug, accessibility, refactor

#263 hotfix: Correct AE Foundation text/logo & reorder `<GamesShowcase/>` placement
  public/assets/images/audio-console/ae-foundation-logo.png
  public/assets/images/audio-console/american-eagle-foundation-logo.png
  src/pages/AccessibilityStudio/AccessibilityStudio.vue
  src/pages/AudioConsole/AudioConsole.vue
Labels: bug, refactor
