Repository Crustaly/audemywebsite, pull requests merged in 2025-05, with the labels that each got.

#151 Add Profile Picture Display for OAuth and Default Login Users
  src/assets/character/default-profile.png
  src/components/Header/Header.vue
Labels: feature

#158 ​Fix: Refactor Sign Up page for responsive design and accessibility
  src/components/AccountPages/Banner.vue
  src/components/Header/Header.vue
  src/components/ScrollUpButton/ScrollUpButton.vue
  src/pages/GameZone/GameZoneCard/GameZoneCard.vue
  src/pages/Impact/CollaboratingSchools/Affiliates.vue
  src/pages/SignUp/SignUp.vue
Labels: bug, accessibility, refactor

#168 Fix: Refactor Log In & School Form for Responsive Design and Accessibility
  public/assets/images/SignUpImg/books.png
  public/assets/images/SignUpImg/orange-star.png
  public/assets/images/SignUpImg/signup-carl.png
  src/components/AccountPages/Banner.vue
  src/components/Header/Header.vue
  src/pages/LogIn/LogIn.vue
  src/pages/SignUp/SignUp.vue
Labels: bug, accessibility, refactor

#160 Fix/Change baseURL to use environment variable for prod and dev environments
  src/pages/ResetPassword/ResetPassword.vue
  src/pages/api/db/get_user.js
  src/pages/api/reset-password.js
  src/pages/api/send-email.js
Labels: bug

#176 re: Updated About Us
  src/pages/AboutUs/Volunteers/Staff.js
Labels: refactor

#180 Fix: Responsive, Accessible Password-Related Pages & Update Banner for Image Flexibility
  public/assets/images/SignUpImg/Group 1010.png
  public/assets/images/SignUpImg/Group 1106.png
  public/assets/images/SignUpImg/Group 878.png
  public/assets/images/SignUpImg/Group 895.png
  src/components/AccountPages/Banner.vue
  src/pages/ForgotPassword/ForgotPassword.vue
  src/pages/ForgotPassword/ResetLinkSent.vue
  src/pages/ResetPassword/ResetConfirm.vue
  src/pages/ResetPassword/ResetLandingPage.vue
  src/pages/ResetPassword/ResetPassword.vue
Labels: bug, accessibility, refactor

#186 fix: Banner.vue typos and Prettier syntax issues
  src/components/AccountPages/Banner.vue
Labels: bug
