Repository Crustaly/audemywebsite, pull requests merged in 2025-04, with the labels that each got.

#89 Enhancement: Add GitHub Issue Templates for Bug, Feature, and Enhancement
  .github/bug_report.yml
  .github/config.yml
  .github/enhancement_request.yml
  .github/feature_request.yml
Labels: documentation, feature

#90 Revert "Enhancement: Add GitHub Issue Templates for Bug, Feature, and Enhancement"
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/enhancement_request.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
Labels: duplicate, help wanted

#99 Fix: Added number format with comma in correct answer lists
  public/assets/questionsDb/multiplication.json
  src/Utilities/playAudio.js
  src/pages/GameZone/GameZone.vue
  src/pages/GameZone/GameZoneList/AdditionGame.vue
  src/pages/GameZone/GameZoneList/CarCounting.vue
  src/pages/GameZone/GameZoneList/ColorGame.vue
  src/pages/GameZone/GameZoneList/DefinitionDetective.vue
  src/pages/GameZone/GameZoneList/DivisionDuel.vue
  src/pages/GameZone/GameZoneList/FruitFrenzy.vue
  src/pages/GameZone/GameZoneList/MonkeyMadness.vue
  src/pages/GameZone/GameZoneList/MultiplicationMadness.vue
  src/pages/GameZone/GameZoneList/OddOneOut.vue
  src/pages/GameZone/GameZoneList/PartOfSpeech.vue
  src/pages/GameZone/GameZoneList/PolarPairing.vue
  src/pages/GameZone/GameZoneList/ShapeShark.vue
  src/pages/GameZone/GameZoneList/SpellingBee.vue
  src/pages/GameZone/GameZoneList/SubtractionGame.vue
  src/pages/GameZone/GameZoneList/SyllableSorting.vue
  src/pages/GameZone/GameZoneList/Vocab.vue
Labels: bug

#109 hotfix: Updated map and added a school to list 🛠️
  src/pages/Impact/CollaboratingSchools/Affiliates.vue
  src/pages/Impact/CollaboratingSchools/Map.vue
Labels: refactor, priority: medium

#112 hotfix: Release/bug fixes
  public/assets/questionsDb/multiplication.json
  src/Utilities/playAudio.js
  src/pages/GameZone/GameZone.vue
  src/pages/GameZone/GameZoneList/AdditionGame.vue
  src/pages/GameZone/GameZoneList/CarCounting.vue
  src/pages/GameZone/GameZoneList/ColorGame.vue
  src/pages/GameZone/GameZoneList/DefinitionDetective.vue
  src/pages/GameZone/GameZoneList/DivisionDuel.vue
  src/pages/GameZone/GameZoneList/FruitFrenzy.vue
  src/pages/GameZone/GameZoneList/MonkeyMadness.vue
  src/pages/GameZone/GameZoneList/MultiplicationMadness.vue
  src/pages/GameZone/GameZoneList/OddOneOut.vue
  src/pages/GameZone/GameZoneList/PartOfSpeech.vue
  src/pages/GameZone/GameZoneList/PolarPairing.vue
  src/pages/GameZone/GameZoneList/ShapeShark.vue
  src/pages/GameZone/GameZoneList/SpellingBee.vue
  src/pages/GameZone/GameZoneList/SubtractionGame.vue
  src/pages/GameZone/GameZoneList/SyllableSorting.vue
  src/pages/GameZone/GameZoneList/Vocab.vue
Labels: feature, priority: high

#111 Refactor/performance tweaks
  src/pages/GameZone/GameZoneList/AdditionGame.vue
  src/pages/GameZone/GameZoneList/CarCounting.vue
  src/pages/GameZone/GameZoneList/ColorGame.vue
  src/pages/GameZone/GameZoneList/DefinitionDetective.vue
  src/pages/GameZone/GameZoneList/DivisionDuel.vue
  src/pages/GameZone/GameZoneList/FruitFrenzy.vue
  src/pages/GameZone/GameZoneList/MonkeyMadness.vue
  src/pages/GameZone/GameZoneList/MultiplicationMadness.vue
  src/pages/GameZone/GameZoneList/OddOneOut.vue
  src/pages/GameZone/GameZoneList/PartOfSpeech.vue
  src/pages/GameZone/GameZoneList/PolarPairing.vue
  src/pages/GameZone/GameZoneList/ShapeShark.vue
  src/pages/GameZone/GameZoneList/SpellingBee.vue
  src/pages/GameZone/GameZoneList/SubtractionGame.vue
  src/pages/GameZone/GameZoneList/SyllableSorting.vue
  src/pages/GameZone/GameZoneList/Vocab.vue
  src/router/index.js
Labels: documentation, refactor, priority: low

#133 Adding appropriate messages for error handling on the frontend
  src/pages/ForgotPassword/ForgotPassword.vue
  src/pages/LogIn/LogIn.vue
  src/pages/LogIn/temp_login.vue
  src/pages/ResetPassword/ResetPassword.vue
  src/pages/SignUp/SignUp.js
  src/pages/SignUp/SignUp.vue
Labels: bug

#119 Major Release - bug fixes and login system
  package-lock.json
  package.json
  prisma/migrations/20250304024523_update_level_data_json/migration.sql
  prisma/migrations/20250304182334_updated_user_name_to_email/migration.sql
  prisma/migrations/20250324132515_new_db/migration.sql
  prisma/schema.prisma
  public/assets/images/about-us/volunteers/ankita.png
  public/assets/images/about-us/volunteers/doohwan.png
  public/assets/images/about-us/volunteers/isabelle.png
  public/assets/images/about-us/volunteers/jesus.png
  public/assets/images/about-us/volunteers/rajat.png
  src/components/Header/Header.vue
  src/main.js
  src/pages/AboutUs/Volunteers/Staff.js
  src/pages/ForgotPassword/ForgotPassword.vue
  src/pages/ForgotPassword/ResetLinkSent.vue
  src/pages/GameZone/GameZone.vue
  src/pages/GameZone/GameZoneList/AdditionGame.vue
  src/pages/GameZone/GameZoneList/CarCounting.vue
  src/pages/GameZone/GameZoneList/ColorGame.vue
  src/pages/GameZone/GameZoneList/DefinitionDetective.vue
  src/pages/GameZone/GameZoneList/DivisionDuel.vue
  src/pages/GameZone/GameZoneList/FruitFrenzy.vue
  src/pages/GameZone/GameZoneList/MonkeyMadness.vue
  src/pages/GameZone/GameZoneList/MultiplicationMadness.vue
  src/pages/GameZone/GameZoneList/OddOneOut.vue
  src/pages/GameZone/GameZoneList/PartOfSpeech.vue
  src/pages/GameZone/GameZoneList/PolarPairing.vue
  src/pages/GameZone/GameZoneList/ShapeShark.vue
  src/pages/GameZone/GameZoneList/SpellingBee.vue
  src/pages/GameZone/GameZoneList/SubtractionGame.vue
  src/pages/GameZone/GameZoneList/SyllableSorting.vue
  src/pages/GameZone/GameZoneList/Vocab.vue
  src/pages/Header/GamePagesHeader.vue
  src/pages/LogIn/LogIn.vue
  src/pages/LogIn/temp_login.vue
  src/pages/ResetPassword/ResetConfirm.vue
  src/pages/ResetPassword/ResetLandingPage.vue
  src/pages/ResetPassword/ResetPassword.vue
  src/pages/SignUp/SignUp.js
  src/pages/SignUp/SignUp.vue
  src/pages/api/auth/google.js
  src/pages/api/auth/login.js
  src/pages/api/auth/signup.js
  src/pages/api/db/get_user.js
  src/pages/api/db/update_user_school.js
  src/pages/api/reset-password.js
  src/pages/api/send-email.js
  src/pages/api/server.js
  src/router/index.js
  vercel.json
Labels: feature, breaking-change, refactor, priority: high

#137 feature: Added accessible, responsive, page-based game dropdown menu
  src/pages/GameZone/GameZone.vue
  src/pages/GameZone/GameZoneCard/GameZoneCard.vue
Labels: feature, accessibility

#135 feat: 🎸 Add a Troubleshooting Page
  public/assets/gameImages/buttons/info.png
  public/assets/images/troubleshooting/01-01.png
  public/assets/images/troubleshooting/01-02.png
  public/assets/images/troubleshooting/01-03.png
  public/assets/images/troubleshooting/01-04.png
  public/assets/images/troubleshooting/01-05.png
  public/assets/images/troubleshooting/alert.png
  public/assets/troubleshootingDB/troubleshooting.json
  src/pages/Footer/GamePagesFooter.vue
  src/pages/GameZone/GameZoneList/AdditionGame.vue
  src/pages/GameZone/GameZoneList/CarCounting.vue
  src/pages/GameZone/GameZoneList/ColorGame.vue
  src/pages/GameZone/GameZoneList/DefinitionDetective.vue
  src/pages/GameZone/GameZoneList/DivisionDuel.vue
  src/pages/GameZone/GameZoneList/FruitFrenzy.vue
  src/pages/GameZone/GameZoneList/MonkeyMadness.vue
  src/pages/GameZone/GameZoneList/MultiplicationMadness.vue
  src/pages/GameZone/GameZoneList/OddOneOut.vue
  src/pages/GameZone/GameZoneList/PartOfSpeech.vue
  src/pages/GameZone/GameZoneList/PolarPairing.vue
  src/pages/GameZone/GameZoneList/ShapeShark.vue
  src/pages/GameZone/GameZoneList/SpellingBee.vue
  src/pages/GameZone/GameZoneList/SubtractionGame.vue
  src/pages/GameZone/GameZoneList/SyllableSorting.vue
  src/pages/GameZone/GameZoneList/Vocab.vue
  src/pages/Troubleshooting/Troubleshooting.vue
  src/router/index.js
Labels: feature

#141 Refactor: Added responsive footer & navbar, fixed layout, and aligned logo & nav items
  src/Utilities/checkDeviceType.js
  src/components/Footer/Footer.vue
  src/components/Header/Header.vue
  src/pages/AboutUs/AboutUs.vue
  src/pages/GameZone/GameZone.vue
  src/pages/Home/Home.vue
  src/pages/Impact/Impact.vue
  src/pages/OurProjects/OurProjects.vue
Labels: accessibility, refactor
